CONTEXT_OVERRIDES = {
    'course_s_1_l6_o7': {'ru':'Опубликуй пост','thai':'โพสต์ข้อความเลยครับ','phonetic':'phóot khɔ̂ɔ-khwaam loei khráp','tip':'Попроси или предложи опубликовать пост.'},
    'course_s_1_l6_o7__part_2': {'ru':'Оставь комментарий','thai':'แสดงความคิดเห็นด้วยครับ','phonetic':'sà-dɛɛng khwaam-khít-hěn dûai khráp','tip':'Попроси оставить комментарий под постом.'},
    'course_s_3_l3_o7__part_2': {'ru':'Что ты чувствуешь?','thai':'รู้สึกยังไงครับ','phonetic':'rʉ́ʉ-sʉ̀k yang ngai khráp','tip':'Спроси о чувствах после личной истории.'},
    'course_s_3_l5_o6__part_2': {'ru':'Это слово используют в обычной речи?','thai':'คำนี้ใช้ในชีวิตประจำวันไหมครับ','phonetic':'kham níi chái nai chii-wít bprà-jam-wan mái khráp','tip':'Уточни, звучит ли слово естественно вне учебника.'},
    'course_s_5_l1_o6__part_2': {'ru':'Ты со мной флиртуешь?','thai':'กำลังจีบผมอยู่เหรอครับ','phonetic':'gam-lang jìip phǒm yùu rǒe khráp','tip':'Только для лёгкого личного разговора.'},
    'course_s_5_l2_o3__part_2': {'ru':'Мне это интересно.','thai':'เรื่องนี้น่าสนใจครับ','phonetic':'rʉ̂ang níi nâa-sǒn-jai khráp','tip':'Скажи, что тема или предложение тебе интересно.'},
    'course_s_5_l3_o5': {'ru':'Ты намекаешь?','thai':'กำลังพูดเป็นนัยอยู่เหรอครับ','phonetic':'gam-lang phûut bpen-nai yùu rǒe khráp','tip':'Уточни, говорит ли человек намёками.'},
    'course_s_5_l3_o5__part_2': {'ru':'Тебе это интересно?','thai':'คุณสนใจเรื่องนี้ไหมครับ','phonetic':'khun sǒn-jai rʉ̂ang níi mái khráp','tip':'Уточни интерес собеседника к теме.'},
    'course_s_5_l6_o6__part_2': {'ru':'Давай обозначим границы.','thai':'เรามาตกลงเรื่องขอบเขตกันนะครับ','phonetic':'rao maa dtok-long rʉ̂ang khɔ̀ɔp-khèet gan ná khráp','tip':'Спокойно обозначь границы в личном разговоре.'},
    'course_s_6_l5_o4': {'ru':'Давай поиграем.','thai':'มาเล่นกันเถอะครับ','phonetic':'maa lên gan thòe khráp','tip':'Предложи совместную игру.'},
    'course_s_6_l5_o4__part_2': {'ru':'Давай поедим.','thai':'ไปกินข้าวกันเถอะครับ','phonetic':'bpai gin khâao gan thòe khráp','tip':'Предложи вместе поесть.'},
    'course_s_6_l5_o6': {'ru':'Мы сейчас на пляже.','thai':'ตอนนี้เราอยู่ที่ชายหาดครับ','phonetic':'dtaawn-níi rao yùu thîi chaai-hàat khráp','tip':'Назови место, когда объясняешь, где вы находитесь.'},
    'course_s_6_l5_o6__part_2': {'ru':'Мы сейчас в кафе.','thai':'ตอนนี้เราอยู่ที่คาเฟ่ครับ','phonetic':'dtaawn-níi rao yùu thîi kaa-fɛɛ khráp','tip':'Назови место встречи.'},
    'course_long_4_l4_o3': {'ru':'Машину угнали.','thai':'รถถูกขโมยครับ','phonetic':'rót thùuk khà-mooi khráp','tip':'Сообщи о краже машины.'},
    'course_long_4_l4_o3__part_2': {'ru':'Произошло ДТП.','thai':'เกิดอุบัติเหตุทางรถยนต์ครับ','phonetic':'gə̀ət ù-bàt-tì-hèet thaang rót-yon khráp','tip':'Сообщи о дорожно-транспортном происшествии.'},
    'course_long_4_l6_o7': {'ru':'Я потерял ключи.','thai':'ผมทำกุญแจหายครับ','phonetic':'phǒm tham gun-jae hǎai khráp','tip':'Сообщи, что ключи потеряны.'},
    'course_long_7_l3_o4': {'ru':'Я смотрю дорамы.','thai':'ผมดูละครเกาหลีครับ','phonetic':'phǒm duu lá-khɔɔn gào-lǐi khráp','tip':'Расскажи, что смотришь корейские дорамы.'},
    'course_long_7_l3_o4__part_2': {'ru':'Я смотрю сериал.','thai':'ผมดูซีรีส์ครับ','phonetic':'phǒm duu sii-rîit khráp','tip':'Расскажи, что смотришь сериал.'},
    'course_s_1_l6_o7__part_2': {'ru':'Оставь комментарий','thai':'แสดงความคิดเห็นด้วยครับ','phonetic':'sà-dɛɛng khwaam-khít-hěn dûai khráp','tip':'Попроси оставить комментарий под постом.'},
    'course_long_1_l4_o5': {'ru':'Передай это, пожалуйста.','thai':'ช่วยเอาไปให้หน่อยครับ','phonetic':'chûai ao bpai hâi nòi khráp','tip':'Попроси передать предмет другому человеку.'},
    'course_long_1_l4_o5__part_2': {'ru':'Я скоро вернусь.','thai':'เดี๋ยวผมกลับมาครับ','phonetic':'dĭao phǒm glàp maa khráp','tip':'Скажи, что ненадолго уходишь и вернёшься.'},
    'course_long_2_l1_o6': {'ru':'Мне нужна виза.','thai':'ผมต้องการวีซ่าครับ','phonetic':'phǒm dtông-gaan wii-sǎa khráp','tip':'Объясни, что тебе нужна виза.'},
    'course_long_2_l1_o6__part_2': {'ru':'Вот мои документы.','thai':'นี่คือเอกสารของผมครับ','phonetic':'nîi khʉʉ èek-gà-sǎan khɔ̌ɔng phǒm khráp','tip':'Передай документы сотруднику.'},
    'course_long_4_l4_o3': {'ru':'Машину угнали.','thai':'รถของผมถูกขโมยครับ','phonetic':'rót khɔ̌ɔng phǒm thùuk khà-mooi khráp','tip':'Сообщи полиции о краже автомобиля.'},
    'course_long_4_l4_o3__part_2': {'ru':'Произошло ДТП.','thai':'เกิดอุบัติเหตุครับ','phonetic':'gə̀ət ù-bàt-tì-hèet khráp','tip':'Сообщи о дорожно-транспортном происшествии.'},
    'course_e_1_l6_o5': {'ru':'Скажу мягче.','thai':'ผมจะพูดให้นุ่มนวลขึ้นครับ','phonetic':'phǒm jà phûut hâi nûm-nuan khʉ̂n khráp','tip':'Пообещай выразиться мягче.'},
    'course_e_1_l6_o5__part_2': {'ru':'Объясню понятнее.','thai':'ผมจะอธิบายให้ชัดเจนขึ้นครับ','phonetic':'phǒm jà à-thí-baai hâi chát-jen khʉ̂n khráp','tip':'Пообещай объяснить понятнее.'},
    'course_e_1_l6_o6': {'ru':'Давайте это обсудим.','thai':'มาคุยเรื่องนี้กันครับ','phonetic':'maa khui rʉ̂ang níi gan khráp','tip':'Предложи спокойно обсудить конкретную тему.'},
    'course_e_4_l1_o3': {'ru':'Без обид, хорошо?','thai':'อย่าโกรธกันนะครับ','phonetic':'yàa gròot gan ná khráp','tip':'Смягчи несогласие перед важным замечанием.'},
    'course_e_4_l4_o5': {'ru':'Скажи помягче, пожалуйста.','thai':'ช่วยพูดเบาๆหน่อยครับ','phonetic':'chûai phûut bao-bao nòi khráp','tip':'Попроси сделать тон мягче.'},
    'course_e_5_l6_o6__part_2': {'ru':'Объясни яснее, пожалуйста.','thai':'ช่วยอธิบายให้ชัดเจนหน่อยครับ','phonetic':'chûai à-thí-baai hâi chát-jen nòi khráp','tip':'Попроси объяснить понятнее.'},
    'course_s_1_l6_o7': {'ru':'Опубликуй пост.','thai':'โพสต์ข้อความเลยครับ','phonetic':'phóot khɔ̂ɔ-khwaam loei khráp','tip':'Попроси опубликовать подготовленный пост.'},
    'course_l_3_l3_o9': {'ru':'На ценнике другая цена.','thai':'ราคาบนป้ายไม่ตรงครับ','phonetic':'raa-khaa bon bpâai mâi dtrong khráp','tip':'Сообщи, что цена на ценнике не совпадает.'},
    'NEW_course_l_3_remaining_04': {'ru':'На кассе другая сумма.','thai':'ยอดเงินที่แคชเชียร์ไม่ตรงครับ','phonetic':'yɔ̂ɔt ngoen thîi khaet-chîa mâi dtrong khráp','tip':'Сообщи, что итоговая сумма на кассе неверна.'},
    'course_l_6_l3_o8': {'ru':'Когда будет готово?','thai':'จะเสร็จเมื่อไหร่ครับ','phonetic':'jà sèt mûea-rài khráp','tip':'Спроси срок готовности ремонта.'},
    'course_l_6_l7_o6': {'ru':'Когда можно забрать?','thai':'มารับได้เมื่อไหร่ครับ','phonetic':'maa ráp dâi mûea-rài khráp','tip':'Спроси, когда можно забрать отремонтированную вещь.'},
    'course_l_6_l7_o11': {'ru':'Позвоните, когда закончите.','thai':'เสร็จแล้วโทรบอกผมด้วยครับ','phonetic':'sèt láeo thoo bòk phǒm dûai khráp','tip':'Попроси позвонить после ремонта.'},
    'NEW_course_l_6_remaining_04': {'ru':'Позвоните мне по этому номеру.','thai':'โทรหาผมตามเบอร์นี้ด้วยครับ','phonetic':'thoo hǎa phǒm dtaam bəə níi dûai khráp','tip':'Оставь номер для связи.'},
    'course_l_11_l3_o9': {'ru':'Когда начинается фестиваль?','thai':'เทศกาลเริ่มกี่โมงครับ','phonetic':'thêet-sà-gaan rə̂əm gìi moong khráp','tip':'Спроси время начала фестиваля.'},
    'NEW_course_l_11_remaining_01': {'ru':'Фестиваль в какой день?','thai':'เทศกาลจัดวันไหนครับ','phonetic':'thêet-sà-gaan jàt wan nǎi khráp','tip':'Спроси, в какой день проходит фестиваль.'},
    'course_l_13_l1_o8': {'ru':'Когда вы сможете починить?','thai':'จะซ่อมได้เมื่อไหร่ครับ','phonetic':'jà sɔ̂m dâi mûea-rài khráp','tip':'Спроси, когда мастер сможет начать ремонт.'},
    'course_l_13_l3_o8': {'ru':'Когда вы закончите ремонт?','thai':'จะซ่อมเสร็จเมื่อไหร่ครับ','phonetic':'jà sɔ̂m sèt mûea-rài khráp','tip':'Спроси срок окончания ремонта.'},
    'course_l_13_l4_o6__part_2': {'ru':'Когда курьер приедет?','thai':'ไรเดอร์จะมาถึงเมื่อไหร่ครับ','phonetic':'rai-dəə jà maa-thʉ̌ng mûea-rài khráp','tip':'Спроси время прибытия курьера.'},
    'NEW_course_l_13_remaining_02': {'ru':'Когда заказ будет у вас?','thai':'ออเดอร์จะถึงคุณเมื่อไหร่ครับ','phonetic':'ɔɔ-də̂ə jà thʉ̌ng khun mûea-rài khráp','tip':'Спроси, когда заказ прибудет к получателю.'},
    'course_l_15_l6_o9': {'ru':'Спасибо за помощь.','thai':'ขอบคุณที่ช่วยนะครับ','phonetic':'khɔ̀ɔp-khun thîi chûai ná khráp','tip':'Поблагодари сотрудника за помощь.'},
    'NEW_course_e_2_wave2_08__part_2': {'ru':'Я понял.','thai':'เข้าใจแล้วครับ','phonetic':'khâo-jai láeo khráp','tip':'Подтверди, что понял инструкцию.'},
    'course_l_3_l3_o9__part_2': {'ru':'На кассе цена другая.','thai':'ราคาที่แคชเชียร์ไม่ตรงครับ','phonetic':'raa-khaa thîi khaet-chîa mâi dtrong khráp','tip':'Сообщи, что цена на кассе отличается.'},
    'course_l_6_l7_o11__part_2': {'ru':'Перезвоните после ремонта.','thai':'ซ่อมเสร็จแล้วโทรกลับด้วยครับ','phonetic':'sɔ̂m sèt láeo thoo glàp dûai khráp','tip':'Попроси перезвонить после окончания ремонта.'},


    'course_l_15_l6_o9__part_2': {'ru':'Я откажусь от покупки.','thai':'ผมไม่รับสินค้าครับ','phonetic':'phǒm mâi ráp sǐn-kháa khráp','tip':'Вежливо откажись от товара на кассе.'},
    'NEW_course_l_15_remaining_04': {'ru':'Мне не нужна скидка.','thai':'ผมไม่รับส่วนลดครับ','phonetic':'phǒm mâi ráp sùan-lót khráp','tip':'Откажись от скидки или дополнительного предложения.'},
    'course_long_4_l6_o7': {'ru':'Я потерял ключи от машины.','thai':'ผมทำกุญแจรถหายครับ','phonetic':'phǒm tham gun-jae rót hǎai khráp','tip':'Сообщи, что потерял ключи от автомобиля.'},
    'course_long_4_l6_o7__part_2': {'ru':'Я потерял ключи от дома.','thai':'ผมทำกุญแจบ้านหายครับ','phonetic':'phǒm tham gun-jae bâan hǎai khráp','tip':'Сообщи, что потерял ключи от дома.'},
    'course_long_5_l5_o4': {'ru':'Когда начинается собрание?','thai':'ประชุมเริ่มกี่โมงครับ','phonetic':'bprà-chum rə̂əm gìi moong khráp','tip':'Спроси время начала собрания.'},
    'NEW_course_long_5_remaining_03': {'ru':'Собрание сегодня?','thai':'วันนี้มีประชุมไหมครับ','phonetic':'wan-níi mii bprà-chum mái khráp','tip':'Уточни, будет ли собрание сегодня.'},
}
