PHONETIC_OVERRIDES = {
    'course_l_13_l7_o4': 'chasomsertmuearaikhrap',
    'course_e_1_l2_o5': 'khoithamkdaikhrap',
    'course_e_2_l6_o4': 'yangmaiserterokhrap',
    'NEW_course_l_2_l1_01': 'paisanambin',
    'NEW_course_l_2_l1_04': 'chottrangani',
    'NEW_course_l_2_l1_06': 'chaibatndaimaikhrap',
    'NEW_course_l_5_l1_06': 'maikhaochaikhrap',
    'NEW_course_l_8_l1_07': 'pelindaimaikhrap',
    'NEW_course_long_4_wave2_04': 'mimuakkannkmaikhrap',
    'NEW_course_e_2_wave2_02': 'nganchasertmuearaikhrap',
    'NEW_course_e_2_wave2_03': 'yangmaisertkhrap',
    'NEW_course_e_2_wave2_05': 'tongthamaraikhrap',
    'NEW_course_s_1_wave2_08': 'mataingthaekaphomkhrap',
    'NEW_course_l_6_remaining_04': 'thonhaphomduaikhrap',
    'NEW_course_l_7_remaining_03': 'khoimnakakdaimaikhrap',
    'NEW_course_l_13_remaining_03': 'chasertmuearaikhrap',
    'NEW_course_e_1_remaining_03': 'khaochailaeokhrap',
    'NEW_course_e_1_remaining_04': 'maikhaochaikhrap',
    'NEW_course_e_4_remaining_01': 'khothotkhrap',
    'NEW_course_e_5_remaining_01': 'thukoingokhemaikhrap',
    'NEW_course_e_5_remaining_03': 'daikhrap',
    'NEW_course_e_5_remaining_04': 'thukoingokhekhrap',
    'NEW_course_s_3_remaining_04': 'khaochailaeokhrap',
    'NEW_course_s_4_remaining_04': 'sertlaeokhrap',
    'NEW_course_s_6_remaining_03': 'kengmak',
}
